### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by sindresorhus** [kevva/play-animal-sounds#3]
It should work offline.

**Comment by kevva** [comment]
How? Sure, we could store all sounds you're playing somewhere, but I don't want to force anyone to download them all on install.

**Comment by sindresorhus** [comment]
@kevva At least cache them for the next time when played. And when offline only pick random between the cached sounds.

**Comment by kevva** [comment]
sgtm

**Comment by kevva** [comment]
@sindresorhus, where do you think they should be saved? `/tmp` is probably not that reliable.

**Comment by sindresorhus** [comment]
@kevva https://github.com/sindresorhus/xdg-basedir#data

**Comment by kevva** [comment]
OS X and Windows?

**Comment by sindresorhus** [comment]
Same. It falls back.
